/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui {
    export class gameOverUI extends Laya.Scene {
		public txtRestart:Laya.TextInput;
		public btnRestart:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("gameOver");
        }
    }
    REG("ui.gameOverUI",gameOverUI);
    export class gameRunUI extends Laya.Scene {
		public btnUp:Laya.Button;
		public btnLeft:Laya.Button;
		public btnDowm:Laya.Button;
		public btnRight:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("gameRun");
        }
    }
    REG("ui.gameRunUI",gameRunUI);
    export class gameStartUI extends Laya.Scene {
		public btnStart:Laya.Button;
		public txtStart:Laya.TextInput;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("gameStart");
        }
    }
    REG("ui.gameStartUI",gameStartUI);
}