/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import GameRestartScene from "./script/GameRestartScene"
import GameRunScene from "./script/GameRunScene"
import GameStartScene from "./script/GameStartScene"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=400;
    static height:number=640;
    static scaleMode:string="fixedauto";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="gameStart.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=false;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("script/GameRestartScene.ts",GameRestartScene);
        reg("script/GameRunScene.ts",GameRunScene);
        reg("script/GameStartScene.ts",GameStartScene);
    }
}
GameConfig.init();